---
default:
  names:
    - Cultivation
    - Dormant Spray
    - Fruit Thinning
    - Hedging
    - Harvest
    - Irrigation
    - Mole/Gopher Abatement
    - Mowing
    - Pre-Pruning
    - Pruning
    - Shoot Thinning
    - Shoot Tucking
    - Spray
    - Suckering
    - Trellis Lifting
    - Trellis Maintenance
    - Tying Vines
    - Weed Abatement
