---
default:
  names:
    - Aedani
    - Aidani
    - Aidini
    - Alamís
    - Alarije
    - Alarijen
    - Albalonga
    - Albana
    - Albanello bianco
    - Albaranzeuli bianco
    - Albarello
    - Albarola
    - Albillo
    - Altesse
    - Alvarinho
    - Amigne
    - Ansonica
    - Ansonica
    - Antao Vaz
    - Aragnan blanc
    - Arbane
    - Arbois
    - Arinto
    - Arneis
    - Arnsburger
    - Arrufiac
    - Arrufiat
    - Arvine
    - Asprinio bianco
    - Assario branco
    - Assyrtico
    - Assyrtiko
    - Athiri
    - Aubin
    - Aubin vert
    - Aurelius
    - Auxerrois blanc
    - Avesso
    - Azal branco
    - Bacchus
    - Baco blanc
    - Baiyu
    - Balzac blanc
    - Banat Riesling
    - Banat Rizling
    - Barbera bianca
    - Barcelo
    - Bariadorgia
    - Baroque
    - Belina
    - Benedino
    - Besgano bianco
    - Bia blanc
    - Biancame
    - Bianchello
    - Bianchetta Trevigiana
    - Bianchetti Genovese
    - Bianco d'Alessano
    - Biancolella
    - Biancone
    - Bical
    - Blanc de Morgex
    - Boais
    - Bombino bianco
    - Borba blanca
    - Bordelesa Zuri
    - Borrado das Moscas
    - Bosco
    - Bourboulenc
    - Bouvier
    - Bratislavské biele
    - Breidecker
    - Brustiano bianco
    - Bual
    - Bukettraube
    - Buonamico
    - Burger
    - Cainho branco
    - Calagraño
    - Camaralet
    - Canari blanc
    - Cape Riesling
    - Carica l'Asino
    - Carignan blanc
    - Cascarolo bianco
    - Catarratto
    - Cayetana
    - Cerceal
    - Cerceal
    - Cereza
    - Chardonnay
    - Chasan
    - Chasselas
    - Chenel
    - Chenin blanc
    - Clairette
    - Clare Riesling
    - Claret de Gascogne
    - Claret de Gers
    - Claverie
    - Cococciola
    - Cocur
    - Coda di Volpe
    - Codega
    - Codega
    - Colombard
    - Completer
    - Cortese
    - Courbu
    - Courtillier Musqué
    - Crato
    - Crato bianco
    - Crato branco
    - Criolla Grande
    - Crouchen
    - Cserszegi Fűszeres
    - Cygne blanc
    - Dattier
    - Debina
    - Debit
    - Diagalves
    - Dimiat
    - Dinka
    - Dona blanca
    - Donzelinho branco
    - Doradillo
    - Drupeggio
    - Durella
    - Ehrenfelser
    - Elbling
    - Emerald Riesling
    - Emir Karasi
    - Encruzado
    - Erbaluce
    - Esagna
    - Escanyavella
    - Esgana Cao
    - Esgana Cão
    - Esquitxagos
    - Ezerjó
    - Faber
    - Faberrebe
    - Falanghina
    - False Pedro
    - Favorita
    - Favorita
    - Fendant
    - Fernao Pires
    - Ferral
    - Fetiaska
    - Fiano
    - Findling
    - Fié
    - Fié gris
    - Fiét
    - Flora
    - Folle blanche
    - Fologosão
    - Francavida
    - Francusa
    - Freiburger
    - Freisamer
    - Friulano
    - Fromenteau
    - Frontignan
    - Furmint
    - Galego Dourado
    - Garganega
    - Garnacha blanca
    - Garnacha blanca
    - Garrido
    - Gellewza
    - Gewürztraminer
    - Giró blanc
    - Gloria
    - Godello
    - Goldburger
    - Goldriesling
    - Gouais blanc
    - Gouveio
    - Gouveio
    - Graisse
    - Grasa
    - Grauburgunder
    - Graševina
    - Grecanico
    - Grechetto
    - Greco
    - Greco bianco
    - Green Hungarian
    - Grenache blanc
    - Grenache blanc
    - Grenache gris
    - Grey Riesling
    - Grignolino
    - Grillo
    - Grk Bijeli
    - Grolleau gris
    - Gros Manseng
    - Gros Plant
    - Grüner Veltliner
    - Guardavalle
    - Guarnaccia bianca
    - Gutedel
    - Gutenborner
    - Hondarrabi Zuri
    - Humagne blanche
    - Huxelrebe
    - Hárslevelű
    - Incrocio Manzoni
    - Inzolia
    - Inzolia
    - Irsai Oliver
    - Irsai Olivér
    - Irsay Oliver
    - Italia
    - Izkiriota Handi
    - Izkiriota Ttipi
    - Izsáki
    - Izsáki Sarfehér
    - Jacquère
    - Jampal
    - Jaén blanca
    - Johannisberg Riesling
    - Juhfark
    - Juwel
    - Kanzler
    - Keknyelu
    - Kerner
    - Klein Rauschling
    - Klevner
    - Klingelberger
    - Knipperle
    - Koshu
    - Ladikino
    - Lado
    - Lagarino bianco
    - Lagorthi
    - Lauzet
    - Lazki Rizling
    - Len de l'El
    - Len de l'Elh
    - Leànyka
    - Listan
    - Loin-de-l'oeil
    - Loureira
    - Luglienga
    - Lumassina
    - Macabeo
    - Macabeo
    - Macabeu
    - Macabeu
    - Maceratino
    - Madeleine Angevine
    - Malagousia
    - Malagoussia
    - Malvar
    - Malvasia
    - Malvoisie
    - Manteudo
    - Mantonico bianco
    - Maria Gomes
    - Marsanne
    - Marzemina bianca
    - Mauzac
    - Melon de Bourgogne
    - Melon de Bourgogne
    - Merlot blanc
    - Merseguera
    - Meslier St-François
    - Mezesfehér
    - Minella bianca
    - Miousap
    - Misket
    - Molette
    - Moll
    - Monbadon
    - Montonico bianco
    - Montu
    - Morio-Muskat
    - Moscatel Rosada
    - Moscatel branco
    - Moscatel de Austria
    - Moscatel de Málaga
    - Moscatell
    - Moscato
    - Moschofilero
    - Moscophilero
    - Mosler
    - Mtsvane
    - Muscadelle
    - Muscadet
    - Muscadet
    - Muscat
    - Muscat Blanc àPetits Grains
    - Muscat Frontignan
    - Muscat Ottonel
    - Muscat of Alexandria
    - Muskateller
    - Nasco
    - Neherleschol
    - Neuburger
    - Nobling
    - Nosiola
    - Nuragus
    - Olaszrizling
    - Ondenc
    - Optima
    - Oraniensteiner
    - Orion
    - Ortega
    - Ortrugo
    - Orémus
    - Pagedebit
    - Pallagrello bianco
    - Palomino
    - Pampanino
    - Pampanuto
    - Pardillo
    - Pardina
    - Parellada
    - Pascal blanc
    - Passerina
    - Pecorello
    - Pecorino
    - Pedro Giménez
    - Pedro Luis
    - Pedro Ximénez
    - Perle
    - Perrum
    - Petit Courbu
    - Petit Manseng
    - Petit Meslier
    - Petite Arvine
    - Picardin
    - Piccolit
    - Piccolito
    - Picolit
    - Picpoul
    - Pigato
    - Pignerol
    - Pignoletto
    - Pineau de la Loire
    - Pinella
    - Pinot bianco
    - Pinot blanc
    - Pinot grigio
    - Pinot gris
    - Pinot jaune
    - Piquepoult
    - Plant de Graisse
    - Planta Fina
    - Planta Nova
    - Plavai
    - Pošip
    - Prié blanc
    - Prosecco
    - Prunesta
    - Rabigato
    - Rabo de Ovelha
    - Raisin blanc
    - Rauschling
    - Regner
    - Reichensteiner
    - Retagliado bianco
    - Rheinriesling
    - Rhoditis
    - Rhoditis
    - Ribolla
    - Rieslaner
    - Riesling
    - Riesling Italico
    - Rivaner
    - Rkatsiteli
    - Rkatsiteli
    - Robola
    - Robola
    - Roditis
    - Roditis
    - Rolle
    - Rolle
    - Rollo
    - Romorantin
    - Rossese bianco
    - Roter Veltliner
    - Rotgipfler
    - Roupeiro
    - Roupeiro
    - Roussanne
    - Roussette
    - Rovello bianco
    - Ruffiac
    - Rèze
    - Sabro
    - Sacy
    - Saint-Pierre Doré
    - Sarfeher
    - Sauvignon blanc
    - Sauvignon gris
    - Sauvignon vert
    - Sauvignonasse
    - Savagnin
    - Savagnin blanc
    - Savatiano
    - Scheurebe
    - Schönburger
    - Septiner
    - Sercial
    - Sercial
    - Sereksia
    - Sideritis
    - Siegerrebe
    - Silvaner
    - Sipon
    - Smederevka
    - Spagnol
    - Spätrot
    - Ste Marie
    - Steen
    - Sultana
    - Sylvaner
    - Symphony
    - Szürkebarát
    - Sárfehér
    - Sémillon
    - Tamares
    - Tamarêz
    - Tamianka
    - Taminga
    - Tamîioasa
    - Tempranillo blanco
    - Terrantez
    - Terret gris
    - Timorasso
    - Tocai Friulano
    - Torbato
    - Torontel
    - Torrontés
    - Tourbat
    - Trajadura
    - Traminac
    - Traminer
    - Tramini
    - Tramini
    - Trbljan
    - Trebbiano
    - Trebbiano
    - Treixadura
    - Tresallier
    - Trousseau gris
    - Tsaoussi
    - Tsolikauri
    - Téoulier
    - Ugni blanc
    - Ugni blanc
    - Verdea
    - Verdeca
    - Verdejo
    - Verdelho
    - Verdello
    - Verdesse
    - Verdia
    - Verdicchio
    - Verdil
    - Verdiso
    - Verdoncho
    - Verdosilla
    - Verduzzo
    - Verduzzo Trevigiano
    - Vermentino
    - Vernaccia
    - Veroga
    - Vespaiola
    - Vilana
    - Vinhao
    - Viognier
    - Viosinho
    - Vital (grape)
    - Vitovska
    - Viura
    - Viura
    - Voskehat
    - Vugava
    - Weissburgunder
    - Weisser Gutedel
    - Weldra
    - Welschriesling
    - Würzer
    - Xarello
    - Xarel·lo
    - Xuri Zerratua
    - Xynisteri
    - Zala Gyöngye
    - Zalema
    - Zefir
    - Zenit
    - Zeusz
    - Zierfandler
